### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by AlexTheGre4t** [AlexTheGre4t/MCTNGIssues#9]
To-do list of everything for MC:TNG
- [x] Ethanol Fixes
- [ ] Fix chunkloading and add ChickenChunks
- [x] Slightly harden Thermal Expansion Recipes
- [x] Vary AE2 recipes
- [ ] Wait for working build of Quadrum and finish adding Ender-pearl drops
- [ ] Add asietweaks - nether quartz ore spawns and better disabled mobs
- [ ] Test the shit out of everything
- [x] Add new mob drops recipes for disabled mobs
- [x] Improve dimension removal and make materials more accessible.
- [ ] Update everything until something fixes itself
- [x] Fix inscriber recipe
- [x] Buff oil spawns

**Comment by BigXplosion** [comment]
build of quadrum that has a fix is coming to keep track of it check [this](http://goo.gl/inH16S) although, the build might be on Betterstorage's side
